---
# file: roles/webservers/handlers/main.yml
- name: restart nginx
  service: name=nginx state=restarted enabled=yes runlevel=default
  sudo: yes


- name: restart redis
  service: name=redis state=restarted enabled=yes runlevel=default
  sudo: yes

- name: start redis
  service: name=redis state=started enabled=yes runlevel=default
  sudo: yes


- name: start jetty
  service: name=jetty state=started enabled=yes runlevel=default
  sudo: yes

- name: start jetty-hightide
  service: name=jetty-hightide state=started enabled=yes runlevel=default
  sudo: yes

- name: restart jetty-hightide
  service: name=jetty-hightide state=restarted enabled=yes runlevel=default
  sudo: yes

- name: save iptables
  shell: service iptables save
  sudo: yes