--- 
# https://github.com/cocoy/ansible-playbooks/blob/master/nginx/tasks/setup.yml

- name: Ensure Nginx repo is installed
  shell:
    rpm -Uvh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    creates=/etc/yum.repos.d/nginx.repo
  sudo: yes
  when: ansible_distribution == 'CentOS'

- name: Add nginx PPA
  apt_repository: repo='ppa:nginx/stable'
  sudo: yes
  when: ansible_distribution == 'Ubuntu'


- name: install nginx
  yum: name=nginx state=latest
  sudo: yes
  when: ansible_distribution == 'CentOS'

- name: Install nginx and update APT package cache
  apt: pkg=nginx state=latest install_recommends=yes
  sudo: yes
  when: ansible_distribution == 'Ubuntu'


- name: copy fixed init for nginx
  copy: src=conf/etc/init.d/nginx.sh dest=/etc/init.d/nginx mode=0755
  sudo: yes
  when: ansible_distribution == 'CentOS'

- name: copy fixed init for nginx
  copy: src=nginx.init dest=/etc/init.d/nginx mode=0755 backup=yes
  sudo: yes
  when: ansible_distribution == 'Ubuntu'


- name:  copy default for nginx
  copy: src=nginx-default dest=/etc/nginx/conf.d/default.conf
  sudo: yes
  when: ansible_distribution == 'CentOS'

- name:  copy default for nginx
  copy: src=nginx-default dest=/etc/nginx/sites-enabled/default
  sudo: yes
  when: ansible_distribution == 'Ubuntu'


- name: write nginx.conf 
  template: src='nginx.conf.j2' dest='/etc/nginx/nginx.conf'
  notify:
    - restart nginx
  sudo: yes