---
##############################################
# Geonetwork - geonetwork-2.10.3-war
# ############################################

# Database creation in dbservers

- name: Ensure geonetwork is downloaded
  get_url:
    url=http://downloads.sourceforge.net/project/geonetwork/GeoNetwork_opensource/v2.10.3/geonetwork.war
    dest=/home/{{ansible_ssh_user}}/geonetwork.war
    mode=0544
  sudo: yes

- name: Extract geonetwork
  shell:
    mkdir -p geonetwork && cd geonetwork && sudo jar xvf /home/{{ansible_ssh_user}}/geonetwork.war
    chdir=/opt/jetty-hightide/webapps/
    creates=/opt/jetty-hightide/webapps/geonetwork/WEB-INF/config.xml
  sudo: yes

- unarchive: src=portti-xsl.tar.gz dest=/opt/jetty-hightide/webapps/geonetwork/xsl/
  sudo: yes

- name: replace broken icu4j version
  shell:
    cp {{ ansible_provisioning_path | default("/vagrant/provisioning") }}/roles/webservers/files/icu4j_2_8.jar . && rm icu4j-2.6.1.jar
    chdir=/opt/jetty-hightide/webapps/geonetwork/WEB-INF/lib/
    removes=/opt/jetty-hightide/webapps/geonetwork/WEB-INF/lib/icu4j-2.6.1.jar
  sudo: yes

- name: copy config for portti
  copy: src=config-portti.xml dest=/opt/jetty-hightide/webapps/geonetwork/WEB-INF/config-portti.xml
  notify:
    - start jetty-hightide
  sudo: yes

- name: Configure geonetwork to use PostgreSQL DB
  template: src=geonetwork-config.xml.j2 dest=/opt/jetty-hightide/webapps/geonetwork/WEB-INF/config.xml
  notify:
    - start jetty-hightide
  sudo: yes
