---
- unarchive: src=apache-maven-3.0.5-bin.tar.gz dest=/opt/
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Ubuntu'

- name: Create Maven3 directory link
  file: path=/opt/maven src=/opt/apache-maven-3.0.5 state=link
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Ubuntu'

- name: Set mvn link
  command: update-alternatives --install /usr/bin/mvn mvn /opt/maven/bin/mvn 1
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Ubuntu'

- name: Install Maven3
  portage: package={{item}} state=present sync=yes update=yes
  with_items:
    - dev-java/maven-bin
  sudo: yes
  when: ansible_distribution == 'Gentoo'
