---
# file: roles/webservers/tasks/main.yml

- include: install_java7.yml
- include: install_maven.yml
- include: install_nginx.yml
- include: install_redis.yml
- include: install_jetty.yml
- include: install_nodejs.yml
- include: install_oskari.yml
- include: install_geoserver.yml
- include: install_geonetwork.yml

- name: Ensure nginx services are started
  service: name=nginx state=started enabled=yes
  sudo: yes

- name: Ensure jetty services are started
  service: name=jetty state=started enabled=yes
  sudo: yes

- name: Ensure jetty-hightide services are started
  service: name=jetty-hightide state=started enabled=yes
  sudo: yes

- name: Ensure redis services are started
  service: name=redis state=started enabled=yes
  sudo: yes